name: Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare - Checkout
        uses: actions/checkout@v4.0.0

      - name: Prepare - Inject short Variables
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Prepare - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Build - BUILD
        uses: docker/build-push-action@v4.2.1
        with:
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: service/on-providers/Dockerfile
          tags: on-local      

      - name: Publish - Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish - Rename Tags
        if: github.event_name != 'pull_request'
        run: |
          docker tag on-local ghcr.io/open-notifications/open-notifications:dev
          docker tag on-local ghcr.io/open-notifications/open-notifications:dev-${{ env.BUILD_NUMBER }}
    
      - name: Publish - Push Tags
        if: github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/open-notifications/open-notifications:dev
          docker push ghcr.io/open-notifications/open-notifications:dev-${{ env.BUILD_NUMBER }}